### ISSUE TITLE
Implement random number seed

### ISSUE THREAD

**Issue by zinroc** [boompig/arena#17]
TODO

**Comment by boompig** [comment]
Done

**Comment by zinroc** [comment]
Done with which commit?

**Comment by zinroc** [comment]
![screen shot 2015-09-15 at 12 59 53 am](https://cloud.githubusercontent.com/assets/4406414/9868387/e35a3154-5b45-11e5-9bbb-323bfb3ab0cb.png)
Also get this when trying to increase timestep, related?

**Comment by zinroc** [comment]
seems to work
